table 50147 "Organization Structure List"
{
    Caption = 'Organization Structure List';
    DataClassification = ToBeClassified;

    fields
    {
        field(1; "Type"; Enum "Organization Structure list")
        {
            Caption = 'Type';
        }
        field(2; "Code"; Code[20])
        {
            Caption = 'Code';
        }
        field(3; Name; Text[100])
        {
            Caption = 'Name';
        }
        field(4; "Province Name"; Text[50])
        {
            Editable = false;
        }
        field(5; "Province Code"; text[20])
        {
            Editable = false;
            DataClassification = ToBeClassified;
        }
        field(6; "Region"; Enum Region)
        {
            Editable = false;
            DataClassification = ToBeClassified;
        }
        field(7; "InsideOutside Valley"; Enum "Outside/Inside Valley")
        {
            Editable = false;
            DataClassification = ToBeClassified;
        }
        field(8; "District code"; Code[20])
        {
            TableRelation = District."District Code";
            trigger OnValidate()
            var
                District: Record District;
            begin
                if District.Get("District code") then begin
                    Validate("District Name", District."District Name");
                    Validate("Province Code", District.Province);
                    Validate("Province Name", District."Province Name");
                    Validate("Region", District.Region);
                    Validate("InsideOutside Valley", District."InsideOutside Valley");
                end else begin
                    Clear("Province Name");
                    Clear("Province Code");
                    Clear("Region");
                    Clear("InsideOutside Valley");
                end;
            end;
        }
        field(9; "Municipality Code"; Code[20])
        {
            TableRelation = "Municipality" where("District Name" = field("District Name"));
            DataClassification = ToBeClassified;
            trigger OnValidate()
            var
                Municipality: Record "Municipality";
            begin
                if Municipality.Get("Municipality Code") then begin
                    Validate("Municipality Name", Municipality."Municipality Name");
                end else begin
                    Clear("Municipality Name");
                end;
            end;
        }
        field(10; "Remote Area Category"; Code[20])
        {
            TableRelation = "Remote Area Category";
            DataClassification = CustomerContent;
        }
        field(11; "Remote Area Reduction"; Code[20])
        {
            TableRelation = "Remote Area Category";
            DataClassification = CustomerContent;
        }
        field(12; "Blocked"; Boolean)
        {
        }
        field(13; "District Name"; Text[50])
        {
            DataClassification = ToBeClassified;
            Editable = false;
        }
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< main
        field(15; "Municipality Name"; Text[50])
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
        field(16; "Sol ID"; Code[20])
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Payroll-Changes
        {
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< main
            DataClassification = ToBeClassified;
            Editable = false;
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
            Caption = 'Sol ID';
            DataClassification = CustomerContent;
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Payroll-Changes
        }
    }
    keys
    {
        key(PK; "Type", Code)
        {
            Clustered = true;
        }
    }
}
