report 50139 "Daily Attendance Update"
{
    // //Min 1.3 --- Added ServiceHistory."Service Event"::"Back From Deputation" Parameter instead of ServiceHistory."Service Event"::"Transfer"
    // //Min 3.13.2022 -- For Update data in "Employee Service History" and "Employee" Table of "Approved" and "Acknowledge" Transfer.
    // //Min 9.26.2022 -- For Document No.Flow in Service History of Re-instiate Transfer.
    // //Min 11.25.2022 -- Sync "Salary Level,Grade" in Emp Attendance Activity.

    ProcessingOnly = true;
    UsageCategory = Tasks;
    ApplicationArea = All;

    dataset
    {
        dataitem(Date; Date)
        {
            dataitem(Employee; Employee)
            {
                DataItemTableView = where(Status = const(Active));
                // RequestFilterFields = "No.", "Employment Type", Status;

                trigger OnAfterGetRecord()
                begin
                    if UpdateDailyAttendance then begin
                        if "Employment Date" = 0D then    // skip blank employment date employee oman
                            CurrReport.Skip;
                        AttendanceMgt.InsertAttendanceLine(Employee."No.", InitialDate, DocNo);
                        if Employee."Employment Type" = Employee."Employment Type"::Contract then
                            StatusInactiveForExpiredContractEmployee;
                    end;
                end;
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< main
                    // if NightShiftAttendanceUpdate then begin
                    //     AttendanceLogRec.Reset;
                    //     AttendanceLogRec.SetRange(Date, InitialDate);
                    //     AttendanceLogRec.SetFilter("Night Shift Check Out Time", '<>%1', 0T);
                    //     AttendanceLogRec.SetRange("Employee ID", Employee."No.");
                    //     if AttendanceLogRec.FindFirst then begin
                    //         AttendLine.Reset;
                    //         AttendLine.SetRange("Employee No.", AttendanceLogRec."Employee ID");
                    //         AttendLine.SetRange("Attendance Date", AttendanceLogRec.Date);
                    //         if AttendLine.FindFirst then begin
                    //             AttendLine."Punch Out Reviewer" := AttendanceLogRec."Punch Out Reviewer";
                    //             AttendLine."Punch Out Check Reviewer" := AttendanceLogRec."Punch Out Check Reviewer";
                    //             AttendLine."Punch out Remarks" := AttendanceLogRec."Punch out Remarks";
                    //             AttendLine."Night Shift Punch Out Time" := AttendanceLogRec."Night Shift Check Out Time";
                    //             AttendLine.Modify;
                    //         end;
                    //         if EmpAttenActRec.Get(AttendanceLogRec."Employee ID", AttendanceLogRec.Date) then begin
                    //             EmpAttenActRec."Punch Out Reviewer" := AttendanceLogRec."Punch Out Reviewer";
                    //             EmpAttenActRec."Punch Out Check Reviewer" := AttendanceLogRec."Punch Out Check Reviewer";
                    //             EmpAttenActRec."Punch out Remarks" := AttendanceLogRec."Punch out Remarks";
                    //             EmpAttenActRec."Night Shift Punch Out Time" := AttendanceLogRec."Night Shift Check Out Time";
                    //             EmpAttenActRec.Modify;
                    //         end;
                    // end;
                    // end;
                end;
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Attendace-Sync

                trigger OnPreDataItem()
                begin
                    SetFilter("Employment Date", '<=%1', InitialDate);
                    SetRange(Status, Employee.Status::Active); //Min 8.26.2022
                end;
            }

            trigger OnAfterGetRecord()
            begin
                Clear(InitialDate);
                InitialDate := "Period Start";
            end;

            trigger OnPreDataItem()
            begin
                SetRange("Period Start", FromDate, ToDate);
                SetRange("Period Type", "Period Type"::Date);
            end;
        }
    }

    requestpage
    {
        layout
        {
            area(Content)
            {
                field("From Date"; FromDate)
                {
                    ToolTip = 'Specifies the value of the FromDate field.';
                    ApplicationArea = All;
                }
                field("To Date"; ToDate)
                {
                    ToolTip = 'Specifies the value of the ToDate field.';
                    ApplicationArea = All;
                }
                field("Update Attendance"; UpdateDailyAttendance)
                {
                    ToolTip = 'Specifies the value of the UpdateDailyAttendance field.';
                    ApplicationArea = All;
                }
                field("Employee No"; EmployeeNo)
                {
                    TableRelation = Employee."No." where(Status = const("Employee Status"::Active));
                    ToolTip = 'Specifies the value of the EmployeeNo field.';
                    ApplicationArea = All;
                }
            }
        }

        actions { }
    }

    labels { }

    trigger OnPostReport()
    begin
        Message('Success');
    end;

    trigger OnPreReport()
    begin
        AttendanceSetup.Get;
        DocNo := NoSeriesMgt.GetNextNo(AttendanceSetup."Attendance Line No. Series", Today, true);
        IF FromDate = 0D THEN
            FromDate := TODAY - 1;
        IF ToDate = 0D THEN
            ToDate := TODAY;
        if (FromDate = 0D) or (ToDate = 0D) then //Min1.9.23
            Error(Err001);
        if UpdateDailyAttendance then begin
            if Employee.GetFilter("Employment Type") = '' then
                Error(Err003);
        end;
        if FromDate > ToDate then
            Error('From Date %1 must be to date %2.', FromDate, ToDate);

        UserSetup.Get(UserId);
        if not UserSetup."Run Back Date Daily Attend." then
            if FromDate < Today - 1 then
                Error('You are not eligible to run back date daily attendance.');

        if (FromDate > Today) or (ToDate > Today) then //Min
            Error('Cannot run attendance of future date. Please check the date.');
        Employee.SetRange("No.", EmployeeNo);
    end;

    var
        AttendanceSetup: Record "Attendance Setup";
        NoSeriesMgt: Codeunit NoSeriesManagement;
        DocNo, EmployeeNo : Code[20];
        InitialDate: Date;
        AttendanceLine: Record "Attendance Line";
        AttendanceLog: Record "Attendance Log";
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< main
        HRMgt: Codeunit "HR Mgt.";
        LeaveMgt: Codeunit "Leave Mgt.";
        OverTimeMgt: Codeunit "OverTime Mgt";
        AttendanceMgt: Codeunit "Attendance Mgt";
        ServiceHistoryMgt: Codeunit "Service History Mgt";
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Attendace-Sync
        CalendarDescription: Text;
        UpdateDailyAttendance: Boolean;
        FromDate, ToDate : Date;
        UserSetup: Record "User Setup";
        EmployeeAttendanceActivity: Record "Employee Attendance & Activity";
        Err001: Label 'Please Select From Date and To Date.';
        Err003: Label 'Please Select Employement Type for update attendance.';
        EngNep: Record "English-Nepali Date";

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< main
    // local procedure InsertAttendanceLine()
    // var
    //     PayrollEngine: Codeunit "Payroll Engine";
    // begin
    //     Clear(AttendanceLine);
    //     AttendanceLine.Reset;
    //     AttendanceLine.SetRange("Employee No.", Employee."No.");
    //     AttendanceLine.SetRange("Attendance Date", InitialDate);
    //     if not AttendanceLine.FindFirst then begin
    //         AttendanceLine.Init;
    //         AttendanceLine."Document No." := DocNo;
    //         AttendanceLine."Employee No." := Employee."No.";
    //         AttendanceLine.Validate("Employee Working Shift", Employee."Employee Work Shift");
    //         AttendanceLine."Attendance Date" := InitialDate;
    //         //AttendanceLine.CopyFromAttendanceHeader(AttendanceHeader);
    //         AttendanceLine.Insert(false);
    //     end;

    //     if IsHoliday(InitialDate, AttendanceLine.Remarks) then begin
    //         AttendanceLine."Day Type" := AttendanceLine."Day Type"::Holiday;
    //         AttendanceLine."Week Off Day" := 1;
    //         AttendanceLine."Holiday Remarks" := CalendarDescription;
    //     end else begin
    //         AttendanceLine."Day Type" := AttendanceLine."Day Type"::"Working Day";
    //         AttendanceLine."Holiday Remarks" := '';
    //         AttendanceLine."Week Off Day" := 0;
    //     end;
    //     if EmployeeAttendanceActivity.Get(Employee."No.", InitialDate) then
    //         if not EmployeeAttendanceActivity."Attendance Update" then begin
    //             AttendanceLog.Reset;
    //             AttendanceLog.SetCurrentKey("Check In Time");
    //             AttendanceLog.SetAscending("Check In Time", true);
    //             AttendanceLog.SetRange(Date, InitialDate);
    //             AttendanceLog.SetRange("Employee ID", AttendanceLine."Employee No.");
    //             if AttendanceLog.FindFirst then begin
    //                 AttendanceLine.Validate("Check In Time", AttendanceLog."Check In Time");
    //                 // AttendanceLine.Validate("Check Out Time", AttendanceLog."Check Out Time");
    //                 // AttendanceLine.Validate("Punch Out Reviewer", AttendanceLog."Punch Out Reviewer"); //Min 8.25.2022
    //                 // AttendanceLine.Validate("Punch Out Check Reviewer", AttendanceLog."Punch Out Check Reviewer"); //Min 8.25.2022
    //                 // AttendanceLine.Validate("Punch out Remarks", AttendanceLog."Punch out Remarks"); //Min 8.29.2022
    //                 // AttendanceLine.Validate("Night Shift Punch Out Time", AttendanceLog."Night Shift Check Out Time"); //Min 12.05.2022
    //                 if (AttendanceLine."Check In Time" <> 0T) then begin
    //                     AttendanceLine."Entry Type" := AttendanceLine."Entry Type"::Present;
    //                     AttendanceLine.Validate("Present Day", 1);
    //                 end;
    //             end;
    //         end;
    //     // to get Checkout time
    //     if EmployeeAttendanceActivity.Get(Employee."No.", InitialDate) then
    //         if not EmployeeAttendanceActivity."Attendance Update" then begin
    //             AttendanceLog.Reset;
    //             AttendanceLog.SetCurrentKey("Check In Time");
    //             AttendanceLog.SetAscending("Check In Time", true);
    //             AttendanceLog.SetRange(Date, InitialDate);
    //             AttendanceLog.SetRange("Employee ID", AttendanceLine."Employee No.");
    //             if AttendanceLog.Findlast then begin
    //                 if AttendanceLog."Check In Time" >= (AttendanceSetUp."Check Out From") then
    //                     AttendanceLine.Validate("Check Out Time", AttendanceLog."Check In Time");
    //             end;
    //         end;
    //     EngNep.Reset; //Min 1.25.2023
    //     EngNep.SetRange("English Date", InitialDate);
    //     if EngNep.FindFirst then
    //         AttendanceLine.Week := EngNep.Week;
    //     AttendanceLine.Modify(false);

    //     PayrollEngine.PrepareEmployeeDailyActivity(AttendanceLine."Employee No.", InitialDate, InitialDate, true);

    //     ChangeStatusToApproveFromHold;
    // end;

    // local procedure IsHoliday(Date: Date; Remarks: Text[100]): Boolean
    // var
    //     HRMgt: Codeunit "HR Mgt.";
    //     LeaveMgt: Codeunit "Leave Mgt.";
    //     RetrunBool: Boolean;
    // begin
    //     RetrunBool := false;
    //     Clear(CalendarDescription);
    //     RetrunBool := LeaveMgt.GetNonWokingDays(InitialDate, InitialDate, Employee."No.") <> 0;
    //     CalendarDescription := HRMgt.ReturnCalendarDescription;
    //     exit(RetrunBool);
    // end;

    local procedure ScreenOvertime()
    var
        //EmployeeActivity: Record "Employee Activity";
        OverTime: Record OverTime;
        Workshift: Record "Employee Work Shift";
        StartTime: Time;
        EndTime: Time;
        StandardWorkingHrs: Decimal;
        ActualOTHrs: Decimal;
        RejectionRemarks: Text;
        EmployeeAttendanceActivity: Record "Employee Attendance & Activity";
        SalaryLevel: Record "Salary Level";
        SalaryLevelTxt: Text;
    begin
        if not UpdateOvertime then
            exit;

        Workshift.Reset;
        Workshift.FindFirst;
        Workshift.TestField("Start Time");
        Workshift.TestField("End Time");
        Workshift.TestField("Friday End Time");
        Workshift.TestField("Winter Start Date");
        Workshift.TestField("Winter End Date");
        Workshift.TestField("Winter End Time");
        StartTime := 0T;
        EndTime := 0T;
        StandardWorkingHrs := 0;
        SalaryLevelTxt := '';

        StartTime := Workshift."Start Time";

        if HRMgt.IsWinter(InitialDate, Workshift) then begin
            if HRMgt.IsFriday(InitialDate) then
                EndTime := Workshift."Friday End Time"
            else
                EndTime := Workshift."Winter End Time";
        end else begin
            if HRMgt.IsFriday(InitialDate) then
                EndTime := Workshift."Friday End Time"
            else
                EndTime := Workshift."End Time";
        end;

        StandardWorkingHrs := (EndTime - StartTime) / 3600000;
        SalaryLevel.Reset;
        SalaryLevel.SetRange("OT Attachment Mandatory", true);
        if SalaryLevel.FindFirst then
            repeat
                if SalaryLevelTxt = '' then
                    SalaryLevelTxt := SalaryLevel.Code
                else
                    SalaryLevelTxt += '|' + SalaryLevel.Code;
            until SalaryLevel.Next = 0;

        OverTime.Reset;
        OverTime.SetRange(Type, OverTime.Type::Overtime);
        OverTime.SetRange("Start Date", InitialDate);
        OverTime.SetFilter("Salary Level Code", '<>%1', SalaryLevelTxt);
        //EmployeeActivity.SETRANGE("Employee No.",EmployeeNo);
        OverTime.SetRange("Approval Status", OverTime."Approval Status"::Approved);
        if OverTime.FindFirst then
            repeat
                if OverTimeMgt.CheckOvertimeEligibility(OverTime, StartTime, EndTime, StandardWorkingHrs, ActualOTHrs, RejectionRemarks) then begin
                    OverTime."Actual OT Hours" := ActualOTHrs;
                    // OverTime.Validate("Approval Status", OverTime."Approval Status"::Screened); temp commented santosh
                    OverTime.Modify;
                    EmployeeAttendanceActivity.Reset;
                    EmployeeAttendanceActivity.SetRange("Attendance Date", OverTime."Start Date");
                    EmployeeAttendanceActivity.SetRange("Employee No.", OverTime."Employee No.");
                    if EmployeeAttendanceActivity.FindFirst then begin
                        EmployeeAttendanceActivity."OT Day" := 1;
                        EmployeeAttendanceActivity."OT Hrs" := ActualOTHrs;
                        EmployeeAttendanceActivity.Modify(true);
                    end;
                end else begin
                    OverTime."Rejection Remarks" := RejectionRemarks;
                    OverTime."Approval Status" := OverTime."Approval Status"::Rejected;
                    OverTime.Modify;

                    EmployeeAttendanceActivity.Reset;
                    EmployeeAttendanceActivity.SetRange("Attendance Date", OverTime."Start Date");
                    EmployeeAttendanceActivity.SetRange("Employee No.", OverTime."Employee No.");
                    if EmployeeAttendanceActivity.FindFirst then begin
                        EmployeeAttendanceActivity."OT Day" := 0;
                        EmployeeAttendanceActivity."OT Hrs" := ActualOTHrs;
                        EmployeeAttendanceActivity.Modify(true);
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================

    local procedure InsertAttendanceLine()
    var
        PayrollEngine: Codeunit "Payroll Engine";
    begin
        Clear(AttendanceLine);
        AttendanceLine.Reset;
        AttendanceLine.SetRange("Employee No.", Employee."No.");
        AttendanceLine.SetRange("Attendance Date", InitialDate);
        if not AttendanceLine.FindFirst then begin
            AttendanceLine.Init;
            AttendanceLine."Document No." := DocNo;
            AttendanceLine."Employee No." := Employee."No.";
            AttendanceLine.Validate("Employee Working Shift", Employee."Employee Work Shift");
            AttendanceLine."Attendance Date" := InitialDate;
            AttendanceLine.Insert(false);
        end;

        if IsHoliday(InitialDate, AttendanceLine.Remarks) then begin
            AttendanceLine."Day Type" := AttendanceLine."Day Type"::Holiday;
            AttendanceLine."Week Off Day" := 1;
            AttendanceLine."Holiday Remarks" := CalendarDescription;
        end else begin
            AttendanceLine."Day Type" := AttendanceLine."Day Type"::"Working Day";
            AttendanceLine."Holiday Remarks" := '';
            AttendanceLine."Week Off Day" := 0;
        end;
        if EmployeeAttendanceActivity.Get(Employee."No.", InitialDate) then
            if not EmployeeAttendanceActivity."Attendance Update" then begin
                AttendanceLog.Reset;
                AttendanceLog.SetCurrentKey("Check In Time");
                AttendanceLog.SetAscending("Check In Time", true);
                AttendanceLog.SetRange(Date, InitialDate);
                AttendanceLog.SetRange("Employee ID", AttendanceLine."Employee No.");
                if AttendanceLog.FindFirst then begin
                    AttendanceLine.Validate("Check In Time", AttendanceLog."Check In Time");
                    if (AttendanceLine."Check In Time" <> 0T) then begin
                        AttendanceLine."Entry Type" := AttendanceLine."Entry Type"::Present;
                        AttendanceLine.Validate("Present Day", 1);
                    end;
                end;
            end;
        // to get Checkout time
        if EmployeeAttendanceActivity.Get(Employee."No.", InitialDate) then
            if not EmployeeAttendanceActivity."Attendance Update" then begin
                AttendanceLog.Reset;
                AttendanceLog.SetCurrentKey("Check In Time");
                AttendanceLog.SetAscending("Check In Time", true);
                AttendanceLog.SetRange(Date, InitialDate);
                AttendanceLog.SetRange("Employee ID", AttendanceLine."Employee No.");
                if AttendanceLog.Findlast then begin
                    if AttendanceLog."Check In Time" >= (AttendanceSetUp."Check Out From") then
                        AttendanceLine.Validate("Check Out Time", AttendanceLog."Check In Time");
                end;
            end;
        EngNep.Reset; //Min 1.25.2023
        EngNep.SetRange("English Date", InitialDate);
        if EngNep.FindFirst then
            AttendanceLine.Week := EngNep.Week;
        AttendanceLine.Modify(false);

        PayrollEngine.PrepareEmployeeDailyActivity(AttendanceLine."Employee No.", InitialDate, InitialDate, true);

    end;

    local procedure IsHoliday(Date: Date; Remarks: Text[100]): Boolean
    var
        HRMgt: Codeunit "HR Mgt.";
        LeaveMgt: Codeunit "Leave Mgt.";
        RetrunBool: Boolean;
    begin
        RetrunBool := false;
        Clear(CalendarDescription);
        RetrunBool := LeaveMgt.GetNonWokingDays(InitialDate, InitialDate, Employee."No.") <> 0;
        CalendarDescription := HRMgt.ReturnCalendarDescription;
        exit(RetrunBool);
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Attendace-Sync
    end;

    local procedure StatusInactiveForExpiredContractEmployee()
    begin
        if Employee."Contract Expiry Date" <> 0D then
            if Employee."Contract Expiry Date" <= InitialDate then
                Employee.Validate(Status, Employee.Status::Inactive);
    end;

    procedure SetRequestFilterValue(FromDate1: Date; ToDate1: Date; EmpNo1: Code[20]; UpdateAttendance: Boolean)
    begin
        FromDate := FromDate1;
        ToDate := ToDate1;
        EmployeeNo := EmpNo1;
        UpdateDailyAttendance := UpdateAttendance;
    end;
}
